-- Prerrequisito: ejecutar 01_Schema_Tablas.sql antes que este script.
/* ════════════════════════════════════════════════════════════════════════
   SECCIÓN 7 — PROCEDIMIENTOS ALMACENADOS
   Patrón: usp_Listar<Entidad> / usp_Obtener<Entidad> / usp_Insertar<Entidad> /
           usp_Listar_<Entidad>_X_<EntidadPadre>
   Todos usan SCOPE_IDENTITY() (nunca @@IDENTITY) y SET NOCOUNT ON.
   ════════════════════════════════════════════════════════════════════════ */

-- SET QUOTED_IDENTIFIER queda "grabado" en cada procedimiento al momento de su CREATE (a
-- diferencia de casi cualquier otro SET, que es solo de sesión) — si queda OFF, cualquier
-- INSERT/UPDATE/DELETE contra una tabla con índice filtrado (ej. TR_PRODUCTO_ALERGENO desde
-- HU-21) falla en tiempo de ejecución con el error 1934, sin importar el SET de quien llama.
-- sqlcmd (a diferencia de SSMS/ADO.NET) arranca con QUOTED_IDENTIFIER OFF por defecto, así que
-- se fija ON explícitamente aquí para que este script produzca el mismo resultado sin importar
-- la herramienta con la que se ejecute.
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_NULLS ON;
GO

-- ── TM_CATEGORIA ───────────────────────────────────────────────────────────
CREATE PROCEDURE usp_ListarCategoria
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDCATEGORIA, CODIGO, NOMBRE, ACTIVO
    FROM TM_CATEGORIA
    WHERE ACTIVO = 1
    ORDER BY NOMBRE;
END
GO

CREATE PROCEDURE usp_ObtenerCategoria
    @IDCATEGORIA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDCATEGORIA, CODIGO, NOMBRE, ACTIVO, FECHACREA, FECHAMODIFICA
    FROM TM_CATEGORIA
    WHERE IDCATEGORIA = @IDCATEGORIA;
END
GO

CREATE PROCEDURE usp_InsertarCategoria
    @CODIGO      VARCHAR(20),
    @NOMBRE      VARCHAR(50),
    @USUARIOCREA INT,
    @IDCATEGORIA INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TM_CATEGORIA (CODIGO, NOMBRE, USUARIOCREA, FECHACREA)
    VALUES (@CODIGO, @NOMBRE, @USUARIOCREA, GETDATE());

    SET @IDCATEGORIA = SCOPE_IDENTITY();
END
GO

-- ── TM_OBJETIVO ────────────────────────────────────────────────────────────
CREATE PROCEDURE usp_ListarObjetivo
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDOBJETIVO, CODIGO, NOMBRE, ACTIVO
    FROM TM_OBJETIVO
    WHERE ACTIVO = 1
    ORDER BY NOMBRE;
END
GO

CREATE PROCEDURE usp_ObtenerObjetivo
    @IDOBJETIVO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDOBJETIVO, CODIGO, NOMBRE, ACTIVO, FECHACREA, FECHAMODIFICA
    FROM TM_OBJETIVO
    WHERE IDOBJETIVO = @IDOBJETIVO;
END
GO

CREATE PROCEDURE usp_InsertarObjetivo
    @CODIGO      VARCHAR(40),
    @NOMBRE      VARCHAR(60),
    @USUARIOCREA INT,
    @IDOBJETIVO  INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TM_OBJETIVO (CODIGO, NOMBRE, USUARIOCREA, FECHACREA)
    VALUES (@CODIGO, @NOMBRE, @USUARIOCREA, GETDATE());

    SET @IDOBJETIVO = SCOPE_IDENTITY();
END
GO

-- ── TM_ALERGENO ────────────────────────────────────────────────────────────
CREATE PROCEDURE usp_ListarAlergeno
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDALERGENO, NOMBRE, ACTIVO
    FROM TM_ALERGENO
    WHERE ACTIVO = 1
    ORDER BY NOMBRE;
END
GO

CREATE PROCEDURE usp_ObtenerAlergeno
    @IDALERGENO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDALERGENO, NOMBRE, ACTIVO, FECHACREA, FECHAMODIFICA
    FROM TM_ALERGENO
    WHERE IDALERGENO = @IDALERGENO;
END
GO

CREATE PROCEDURE usp_InsertarAlergeno
    @NOMBRE      VARCHAR(100),
    @USUARIOCREA INT,
    @IDALERGENO  INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TM_ALERGENO (NOMBRE, USUARIOCREA, FECHACREA)
    VALUES (@NOMBRE, @USUARIOCREA, GETDATE());

    SET @IDALERGENO = SCOPE_IDENTITY();
END
GO

-- ── TM_USUARIO ─────────────────────────────────────────────────────────────
CREATE PROCEDURE usp_ListarUsuario
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDUSUARIO, NOMBRE, EMAIL, ACTIVO
    FROM TM_USUARIO
    WHERE ACTIVO = 1
    ORDER BY NOMBRE;
END
GO

CREATE PROCEDURE usp_ObtenerUsuario
    @IDUSUARIO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDUSUARIO, NOMBRE, EMAIL, ACTIVO, FECHACREA, FECHAMODIFICA
    FROM TM_USUARIO
    WHERE IDUSUARIO = @IDUSUARIO;
END
GO

-- Requerido por AuthService.login()/estaAutenticado(): la autenticación busca
-- por EMAIL, no por IDUSUARIO.
CREATE PROCEDURE usp_ObtenerUsuario_X_Email
    @EMAIL VARCHAR(254)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDUSUARIO, NOMBRE, EMAIL, PASSWORD, ACTIVO
    FROM TM_USUARIO
    WHERE EMAIL = @EMAIL AND ACTIVO = 1;
END
GO

CREATE PROCEDURE usp_InsertarUsuario
    @NOMBRE      VARCHAR(100),
    @EMAIL       VARCHAR(254),
    @PASSWORD    VARCHAR(256),
    @USUARIOCREA INT,
    @IDUSUARIO   INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TM_USUARIO (NOMBRE, EMAIL, PASSWORD, USUARIOCREA, FECHACREA)
    VALUES (@NOMBRE, @EMAIL, @PASSWORD, @USUARIOCREA, GETDATE());

    SET @IDUSUARIO = SCOPE_IDENTITY();
END
GO

-- ── TM_PRODUCTO ────────────────────────────────────────────────────────────
CREATE PROCEDURE usp_ListarProducto
AS
BEGIN
    SET NOCOUNT ON;
    SELECT P.IDPRODUCTO, P.NOMBRE, P.MARCA, P.IDCATEGORIA, C.NOMBRE AS CATEGORIA,
           P.IDOBJETIVO, O.NOMBRE AS OBJETIVO, P.PRECIO, P.DESCRIPCION,
           P.DOSISRECOMENDADA, P.URLIMAGEN, P.REGISTROSANITARIO, P.ENTIDADREGISTRO, P.STOCK, P.ACTIVO
    FROM TM_PRODUCTO P
    INNER JOIN TM_CATEGORIA C ON C.IDCATEGORIA = P.IDCATEGORIA
    INNER JOIN TM_OBJETIVO  O ON O.IDOBJETIVO  = P.IDOBJETIVO
    WHERE P.ACTIVO = 1
    ORDER BY P.NOMBRE;
END
GO

CREATE PROCEDURE usp_ObtenerProducto
    @IDPRODUCTO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT P.IDPRODUCTO, P.NOMBRE, P.MARCA, P.IDCATEGORIA, C.NOMBRE AS CATEGORIA,
           P.IDOBJETIVO, O.NOMBRE AS OBJETIVO, P.PRECIO, P.DESCRIPCION,
           P.DOSISRECOMENDADA, P.URLIMAGEN, P.REGISTROSANITARIO, P.ENTIDADREGISTRO, P.STOCK,
           P.ACTIVO, P.FECHACREA, P.FECHAMODIFICA
    FROM TM_PRODUCTO P
    INNER JOIN TM_CATEGORIA C ON C.IDCATEGORIA = P.IDCATEGORIA
    INNER JOIN TM_OBJETIVO  O ON O.IDOBJETIVO  = P.IDOBJETIVO
    WHERE P.IDPRODUCTO = @IDPRODUCTO;
END
GO

-- Soporta FiltrosProducto.categoria (catalogo.ts).
CREATE PROCEDURE usp_Listar_Producto_X_Categoria
    @IDCATEGORIA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDPRODUCTO, NOMBRE, MARCA, PRECIO, URLIMAGEN, STOCK
    FROM TM_PRODUCTO
    WHERE IDCATEGORIA = @IDCATEGORIA AND ACTIVO = 1
    ORDER BY NOMBRE;
END
GO

-- Soporta FiltrosProducto.objetivo y ProductoService.obtenerRecomendaciones().
CREATE PROCEDURE usp_Listar_Producto_X_Objetivo
    @IDOBJETIVO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDPRODUCTO, NOMBRE, MARCA, PRECIO, URLIMAGEN, STOCK
    FROM TM_PRODUCTO
    WHERE IDOBJETIVO = @IDOBJETIVO AND ACTIVO = 1
    ORDER BY NOMBRE;
END
GO

CREATE PROCEDURE usp_InsertarProducto
    @NOMBRE            VARCHAR(150),
    @MARCA             VARCHAR(100),
    @IDCATEGORIA       INT,
    @IDOBJETIVO        INT,
    @PRECIO            DECIMAL(10,2),
    @DESCRIPCION       VARCHAR(500),
    @DOSISRECOMENDADA  VARCHAR(200),
    @URLIMAGEN         VARCHAR(500) = NULL,
    @REGISTROSANITARIO VARCHAR(50)  = NULL,
    @ENTIDADREGISTRO   VARCHAR(10)  = NULL,
    @STOCK             INT          = 0,
    @USUARIOCREA       INT,
    @IDPRODUCTO        INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TM_PRODUCTO (
        NOMBRE, MARCA, IDCATEGORIA, IDOBJETIVO, PRECIO, DESCRIPCION,
        DOSISRECOMENDADA, URLIMAGEN, REGISTROSANITARIO, ENTIDADREGISTRO, STOCK,
        USUARIOCREA, FECHACREA
    )
    VALUES (
        @NOMBRE, @MARCA, @IDCATEGORIA, @IDOBJETIVO, @PRECIO, @DESCRIPCION,
        @DOSISRECOMENDADA, @URLIMAGEN, @REGISTROSANITARIO, @ENTIDADREGISTRO, @STOCK,
        @USUARIOCREA, GETDATE()
    );

    SET @IDPRODUCTO = SCOPE_IDENTITY();
END
GO

-- Mantenimiento de catálogo (precio, descripción, stock, etc.) sin borrar/recrear el
-- registro. Hace un SET absoluto de todos los campos editables — pensado para el
-- formulario de edición de un administrador, NO para aplicar deltas de stock
-- concurrentes (ver advertencia de concurrencia en usp_ActualizarStockProducto).
CREATE PROCEDURE usp_ActualizarProducto
    @IDPRODUCTO        INT,
    @NOMBRE            VARCHAR(150),
    @MARCA             VARCHAR(100),
    @IDCATEGORIA       INT,
    @IDOBJETIVO        INT,
    @PRECIO            DECIMAL(10,2),
    @DESCRIPCION       VARCHAR(500),
    @DOSISRECOMENDADA  VARCHAR(200),
    @URLIMAGEN         VARCHAR(500) = NULL,
    @REGISTROSANITARIO VARCHAR(50)  = NULL,
    @ENTIDADREGISTRO   VARCHAR(10)  = NULL,
    @STOCK             INT,
    @ACTIVO            BIT,
    @USUARIOMODIFICA   INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TM_PRODUCTO
    SET NOMBRE            = @NOMBRE,
        MARCA             = @MARCA,
        IDCATEGORIA       = @IDCATEGORIA,
        IDOBJETIVO        = @IDOBJETIVO,
        PRECIO            = @PRECIO,
        DESCRIPCION       = @DESCRIPCION,
        DOSISRECOMENDADA  = @DOSISRECOMENDADA,
        URLIMAGEN         = @URLIMAGEN,
        REGISTROSANITARIO = @REGISTROSANITARIO,
        ENTIDADREGISTRO   = @ENTIDADREGISTRO,
        STOCK             = @STOCK,
        ACTIVO            = @ACTIVO,
        USUARIOMODIFICA   = @USUARIOMODIFICA,
        FECHAMODIFICA     = GETDATE()
    WHERE IDPRODUCTO = @IDPRODUCTO;

    IF @@ROWCOUNT = 0
    BEGIN
        THROW 51002, 'usp_ActualizarProducto: no existe ningún producto con el IDPRODUCTO especificado.', 1;
    END
END
GO

-- Ajuste ATÓMICO de stock por delta (venta = negativo, reposición/corrección de
-- mermas = positivo). A diferencia de usp_ActualizarProducto (SET absoluto, pensado
-- para el formulario de edición), este procedimiento es seguro bajo concurrencia:
-- la condición "STOCK + @CANTIDAD >= 0" se evalúa dentro del mismo UPDATE atómico
-- (SQL Server toma el lock de la fila antes de evaluar el predicado), por lo que
-- dos ventas simultáneas del mismo producto no pueden generar stock negativo
-- (sin esta guarda en el WHERE, un patrón "leer stock, validar en el cliente,
-- luego actualizar" sí sería vulnerable a condición de carrera).
CREATE PROCEDURE usp_ActualizarStockProducto
    @IDPRODUCTO      INT,
    @CANTIDAD        INT,
    @USUARIOMODIFICA INT,
    @NUEVOSTOCK      INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TM_PRODUCTO
    SET STOCK           = STOCK + @CANTIDAD,
        USUARIOMODIFICA = @USUARIOMODIFICA,
        FECHAMODIFICA   = GETDATE()
    WHERE IDPRODUCTO = @IDPRODUCTO
      AND STOCK + @CANTIDAD >= 0;

    IF @@ROWCOUNT = 0
    BEGIN
        THROW 51003, 'usp_ActualizarStockProducto: stock insuficiente o producto inexistente.', 1;
    END

    SELECT @NUEVOSTOCK = STOCK FROM TM_PRODUCTO WHERE IDPRODUCTO = @IDPRODUCTO;
END
GO

-- ── TD_PRODUCTO_INGREDIENTE ────────────────────────────────────────────────
CREATE PROCEDURE usp_Listar_ProductoIngrediente_X_Producto
    @IDPRODUCTO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDPRODUCTOINGREDIENTE, INGREDIENTE
    FROM TD_PRODUCTO_INGREDIENTE
    WHERE IDPRODUCTO = @IDPRODUCTO AND ACTIVO = 1
    ORDER BY IDPRODUCTOINGREDIENTE;
END
GO

CREATE PROCEDURE usp_InsertarProductoIngrediente
    @IDPRODUCTO            INT,
    @INGREDIENTE           VARCHAR(150),
    @USUARIOCREA           INT,
    @IDPRODUCTOINGREDIENTE INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TD_PRODUCTO_INGREDIENTE (IDPRODUCTO, INGREDIENTE, USUARIOCREA, FECHACREA)
    VALUES (@IDPRODUCTO, @INGREDIENTE, @USUARIOCREA, GETDATE());

    SET @IDPRODUCTOINGREDIENTE = SCOPE_IDENTITY();
END
GO

-- ── TD_PRODUCTO_CONTRAINDICACION ───────────────────────────────────────────
CREATE PROCEDURE usp_Listar_ProductoContraindicacion_X_Producto
    @IDPRODUCTO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDPRODUCTOCONTRAINDICACION, DESCRIPCION
    FROM TD_PRODUCTO_CONTRAINDICACION
    WHERE IDPRODUCTO = @IDPRODUCTO AND ACTIVO = 1
    ORDER BY IDPRODUCTOCONTRAINDICACION;
END
GO

CREATE PROCEDURE usp_InsertarProductoContraindicacion
    @IDPRODUCTO                 INT,
    @DESCRIPCION                VARCHAR(300),
    @USUARIOCREA                INT,
    @IDPRODUCTOCONTRAINDICACION INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TD_PRODUCTO_CONTRAINDICACION (IDPRODUCTO, DESCRIPCION, USUARIOCREA, FECHACREA)
    VALUES (@IDPRODUCTO, @DESCRIPCION, @USUARIOCREA, GETDATE());

    SET @IDPRODUCTOCONTRAINDICACION = SCOPE_IDENTITY();
END
GO

-- ── TR_PRODUCTO_ALERGENO ───────────────────────────────────────────────────
CREATE PROCEDURE usp_Listar_ProductoAlergeno_X_Producto
    @IDPRODUCTO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT A.IDALERGENO, A.NOMBRE
    FROM TR_PRODUCTO_ALERGENO PA
    INNER JOIN TM_ALERGENO A ON A.IDALERGENO = PA.IDALERGENO
    WHERE PA.IDPRODUCTO = @IDPRODUCTO AND PA.ACTIVO = 1
    ORDER BY A.NOMBRE;
END
GO

CREATE PROCEDURE usp_InsertarProductoAlergeno
    @IDPRODUCTO         INT,
    @IDALERGENO         INT,
    @USUARIOCREA        INT,
    @IDPRODUCTOALERGENO INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TR_PRODUCTO_ALERGENO (IDPRODUCTO, IDALERGENO, USUARIOCREA, FECHACREA)
    VALUES (@IDPRODUCTO, @IDALERGENO, @USUARIOCREA, GETDATE());

    SET @IDPRODUCTOALERGENO = SCOPE_IDENTITY();
END
GO

-- HU-21 — Transparencia sanitaria persistente: baja lógica (nunca DELETE físico) de las filas
-- vigentes antes de re-insertar la lista editada. Como ACTIVO/USUARIOMODIFICA/FECHAMODIFICA ya
-- existían en estas 3 tablas (ver 01_Schema_Tablas.sql), cada edición queda como una generación
-- nueva y con timestamp propio, sin perder nunca la anterior — la propia tabla es el historial
-- auditable, sin necesitar una tabla de auditoría paralela.
CREATE PROCEDURE usp_Desactivar_ProductoIngrediente_X_Producto
    @IDPRODUCTO       INT,
    @USUARIOMODIFICA  INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TD_PRODUCTO_INGREDIENTE
    SET ACTIVO = 0, USUARIOMODIFICA = @USUARIOMODIFICA, FECHAMODIFICA = GETDATE()
    WHERE IDPRODUCTO = @IDPRODUCTO AND ACTIVO = 1;
END
GO

CREATE PROCEDURE usp_Desactivar_ProductoContraindicacion_X_Producto
    @IDPRODUCTO       INT,
    @USUARIOMODIFICA  INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TD_PRODUCTO_CONTRAINDICACION
    SET ACTIVO = 0, USUARIOMODIFICA = @USUARIOMODIFICA, FECHAMODIFICA = GETDATE()
    WHERE IDPRODUCTO = @IDPRODUCTO AND ACTIVO = 1;
END
GO

CREATE PROCEDURE usp_Desactivar_ProductoAlergeno_X_Producto
    @IDPRODUCTO       INT,
    @USUARIOMODIFICA  INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TR_PRODUCTO_ALERGENO
    SET ACTIVO = 0, USUARIOMODIFICA = @USUARIOMODIFICA, FECHAMODIFICA = GETDATE()
    WHERE IDPRODUCTO = @IDPRODUCTO AND ACTIVO = 1;
END
GO

-- ── TM_DIAGNOSTICO ─────────────────────────────────────────────────────────
-- Historial por usuario (Dashboard, HU-10): equivalente a DiagnosticoService.historial().
CREATE PROCEDURE usp_Listar_Diagnostico_X_Usuario
    @IDUSUARIO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (10) IDDIAGNOSTICO, FECHA, NIVELESTRES, CALIDADSUENO, IDOBJETIVO,
           HORASCONCENTRACION, CONDICIONMEDICA
    FROM TM_DIAGNOSTICO
    WHERE IDUSUARIO = @IDUSUARIO AND ACTIVO = 1
    ORDER BY FECHA DESC;
END
GO

CREATE PROCEDURE usp_ObtenerDiagnostico
    @IDDIAGNOSTICO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDDIAGNOSTICO, IDUSUARIO, FECHA, NIVELESTRES, CALIDADSUENO, IDOBJETIVO,
           HORASCONCENTRACION, CONDICIONMEDICA, ACTIVO, FECHACREA, FECHAMODIFICA
    FROM TM_DIAGNOSTICO
    WHERE IDDIAGNOSTICO = @IDDIAGNOSTICO;
END
GO

-- Reemplaza el campo PerfilCognitivo de Usuario (models/usuario/usuario.ts):
-- se calcula en runtime a partir del diagnóstico más reciente, tal como indica
-- el comentario original del modelo TS, en vez de duplicar el dato en TM_USUARIO.
CREATE PROCEDURE usp_ObtenerPerfilCognitivo_X_Usuario
    @IDUSUARIO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (1) NIVELESTRES, CALIDADSUENO, O.NOMBRE AS OBJETIVOPRINCIPAL
    FROM TM_DIAGNOSTICO D
    INNER JOIN TM_OBJETIVO O ON O.IDOBJETIVO = D.IDOBJETIVO
    WHERE D.IDUSUARIO = @IDUSUARIO AND D.ACTIVO = 1
    ORDER BY D.FECHA DESC;
END
GO

CREATE PROCEDURE usp_InsertarDiagnostico
    @IDUSUARIO          INT,
    @FECHA              DATETIME,
    @NIVELESTRES        INT,
    @CALIDADSUENO       INT,
    @IDOBJETIVO         INT,
    @HORASCONCENTRACION INT,
    @CONDICIONMEDICA    VARCHAR(300) = NULL,
    @USUARIOCREA        INT,
    @IDDIAGNOSTICO      INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TM_DIAGNOSTICO (
        IDUSUARIO, FECHA, NIVELESTRES, CALIDADSUENO, IDOBJETIVO,
        HORASCONCENTRACION, CONDICIONMEDICA, USUARIOCREA, FECHACREA
    )
    VALUES (
        @IDUSUARIO, @FECHA, @NIVELESTRES, @CALIDADSUENO, @IDOBJETIVO,
        @HORASCONCENTRACION, @CONDICIONMEDICA, @USUARIOCREA, GETDATE()
    );

    SET @IDDIAGNOSTICO = SCOPE_IDENTITY();
END
GO

-- ── TR_DIAGNOSTICO_ALERGENO ────────────────────────────────────────────────
CREATE PROCEDURE usp_Listar_DiagnosticoAlergeno_X_Diagnostico
    @IDDIAGNOSTICO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT A.IDALERGENO, A.NOMBRE
    FROM TR_DIAGNOSTICO_ALERGENO DA
    INNER JOIN TM_ALERGENO A ON A.IDALERGENO = DA.IDALERGENO
    WHERE DA.IDDIAGNOSTICO = @IDDIAGNOSTICO AND DA.ACTIVO = 1
    ORDER BY A.NOMBRE;
END
GO

CREATE PROCEDURE usp_InsertarDiagnosticoAlergeno
    @IDDIAGNOSTICO         INT,
    @IDALERGENO            INT,
    @USUARIOCREA           INT,
    @IDDIAGNOSTICOALERGENO INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TR_DIAGNOSTICO_ALERGENO (IDDIAGNOSTICO, IDALERGENO, USUARIOCREA, FECHACREA)
    VALUES (@IDDIAGNOSTICO, @IDALERGENO, @USUARIOCREA, GETDATE());

    SET @IDDIAGNOSTICOALERGENO = SCOPE_IDENTITY();
END
GO

-- ── TR_DIAGNOSTICO_RECOMENDACION ───────────────────────────────────────────
CREATE PROCEDURE usp_Listar_DiagnosticoRecomendacion_X_Diagnostico
    @IDDIAGNOSTICO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT P.IDPRODUCTO, P.NOMBRE, P.MARCA, P.PRECIO, P.URLIMAGEN, P.STOCK
    FROM TR_DIAGNOSTICO_RECOMENDACION DR
    INNER JOIN TM_PRODUCTO P ON P.IDPRODUCTO = DR.IDPRODUCTO
    WHERE DR.IDDIAGNOSTICO = @IDDIAGNOSTICO AND DR.ACTIVO = 1
    ORDER BY P.NOMBRE;
END
GO

CREATE PROCEDURE usp_InsertarDiagnosticoRecomendacion
    @IDDIAGNOSTICO              INT,
    @IDPRODUCTO                 INT,
    @USUARIOCREA                INT,
    @IDDIAGNOSTICORECOMENDACION INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TR_DIAGNOSTICO_RECOMENDACION (IDDIAGNOSTICO, IDPRODUCTO, USUARIOCREA, FECHACREA)
    VALUES (@IDDIAGNOSTICO, @IDPRODUCTO, @USUARIOCREA, GETDATE());

    SET @IDDIAGNOSTICORECOMENDACION = SCOPE_IDENTITY();
END
GO

-- ── TM_PEDIDO ──────────────────────────────────────────────────────────────
-- Historial por usuario (Checkout/Dashboard): equivalente a PedidoService.historial().
CREATE PROCEDURE usp_Listar_Pedido_X_Usuario
    @IDUSUARIO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (10) IDPEDIDO, NUMEROPEDIDO, FECHAPEDIDO, TOTAL, DIRECCIONENVIO,
           CIUDADENVIO, METODOPAGO
    FROM TM_PEDIDO
    WHERE IDUSUARIO = @IDUSUARIO AND ACTIVO = 1
    ORDER BY FECHAPEDIDO DESC;
END
GO

CREATE PROCEDURE usp_ObtenerPedido
    @IDPEDIDO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDPEDIDO, IDUSUARIO, NUMEROPEDIDO, FECHAPEDIDO, TOTAL, NOMBRECLIENTE,
           DIRECCIONENVIO, CIUDADENVIO, TELEFONOCONTACTO, METODOPAGO,
           ACTIVO, FECHACREA, FECHAMODIFICA
    FROM TM_PEDIDO
    WHERE IDPEDIDO = @IDPEDIDO;
END
GO

CREATE PROCEDURE usp_InsertarPedido
    @IDUSUARIO        INT,
    @NUMEROPEDIDO     VARCHAR(50),
    @FECHAPEDIDO      DATETIME,
    @TOTAL            DECIMAL(10,2),
    @NOMBRECLIENTE    VARCHAR(150),
    @DIRECCIONENVIO   VARCHAR(200),
    @CIUDADENVIO      VARCHAR(100),
    @TELEFONOCONTACTO VARCHAR(9),
    @METODOPAGO       VARCHAR(20),
    @USUARIOCREA      INT,
    @IDPEDIDO         INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TM_PEDIDO (
        IDUSUARIO, NUMEROPEDIDO, FECHAPEDIDO, TOTAL, NOMBRECLIENTE,
        DIRECCIONENVIO, CIUDADENVIO, TELEFONOCONTACTO, METODOPAGO,
        USUARIOCREA, FECHACREA
    )
    VALUES (
        @IDUSUARIO, @NUMEROPEDIDO, @FECHAPEDIDO, @TOTAL, @NOMBRECLIENTE,
        @DIRECCIONENVIO, @CIUDADENVIO, @TELEFONOCONTACTO, @METODOPAGO,
        @USUARIOCREA, GETDATE()
    );

    SET @IDPEDIDO = SCOPE_IDENTITY();
END
GO

-- ── TD_PEDIDO_DETALLE ──────────────────────────────────────────────────────
CREATE PROCEDURE usp_Listar_PedidoDetalle_X_Pedido
    @IDPEDIDO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IDPEDIDODETALLE, IDPRODUCTO, NOMBREPRODUCTO, PRECIOUNITARIO, CANTIDAD
    FROM TD_PEDIDO_DETALLE
    WHERE IDPEDIDO = @IDPEDIDO AND ACTIVO = 1
    ORDER BY IDPEDIDODETALLE;
END
GO

-- Inserta la línea de pedido Y descuenta el stock del producto en la MISMA
-- transacción: si no hay stock suficiente, ninguna de las dos operaciones se
-- aplica (evita vender productos sin stock). El UPDATE usa la misma guarda
-- atómica "STOCK >= @CANTIDAD" que usp_ActualizarStockProducto (ver comentario
-- ahí) para que dos compras simultáneas del mismo producto no puedan agotar el
-- stock por debajo de cero.
-- NOTA PARA LA CAPA .NET: esto garantiza atomicidad POR LÍNEA. Si un pedido tiene
-- varias líneas y una falla por falta de stock, las líneas anteriores de ESE MISMO
-- pedido ya se habrán confirmado (COMMIT). Para atomicidad de TODO el pedido
-- (rollback completo si cualquier línea falla), Business.PedidoService debe invocar
-- usp_InsertarPedido + todos los usp_InsertarPedidoDetalle dentro de una única
-- transacción ADO.NET/Dapper (SqlTransaction) y hacer rollback manual si cualquier
-- llamada lanza la excepción de stock insuficiente.
CREATE PROCEDURE usp_InsertarPedidoDetalle
    @IDPEDIDO         INT,
    @IDPRODUCTO        INT,
    @NOMBREPRODUCTO    VARCHAR(150),
    @PRECIOUNITARIO    DECIMAL(10,2),
    @CANTIDAD          INT,
    @USUARIOCREA       INT,
    @IDPEDIDODETALLE   INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRANSACTION;

    UPDATE TM_PRODUCTO
    SET STOCK         = STOCK - @CANTIDAD,
        FECHAMODIFICA = GETDATE()
    WHERE IDPRODUCTO = @IDPRODUCTO
      AND STOCK >= @CANTIDAD;

    IF @@ROWCOUNT = 0
    BEGIN
        ROLLBACK TRANSACTION;
        THROW 51001, 'usp_InsertarPedidoDetalle: stock insuficiente para completar la venta del producto solicitado.', 1;
    END

    INSERT INTO TD_PEDIDO_DETALLE (
        IDPEDIDO, IDPRODUCTO, NOMBREPRODUCTO, PRECIOUNITARIO, CANTIDAD,
        USUARIOCREA, FECHACREA
    )
    VALUES (
        @IDPEDIDO, @IDPRODUCTO, @NOMBREPRODUCTO, @PRECIOUNITARIO, @CANTIDAD,
        @USUARIOCREA, GETDATE()
    );

    SET @IDPEDIDODETALLE = SCOPE_IDENTITY();

    COMMIT TRANSACTION;
END
GO
